# Image
FROM node:12.4-alpine

# Set up work directory
WORKDIR /var/www/app

# Configure host
ENV HOST 0.0.0.0

# Init command
CMD ["sh", "-c", "yarn dev"]
# CMD ["sh", "-c", "npm rebuild node-sass"]
